"""Generates system/blockMeshDict for the Mach 11.3 blunted cone
(Casseau et al. Part Two, Sec. 3.1): 6.35 mm nose radius + 25 deg cone,
5 cm streamwise extension, axisymmetric wedge (4 deg).

Two blocks in the meridian plane:
  A: nose region, body arc (phi in [0, 65 deg]) to outer arc (3 Rn)
  B: cone region, cone surface to slanted outer boundary (35 deg)

Usage: python3 makeBlockMeshDict.py [coarse|fine]
  coarse: (40+80) x 60,  first wall cell ~2e-5 m  (local pipeline checks)
  fine:   (200+400) x 200, first wall cell ~2e-6 m (cluster runs; paper
          uses 600x200 with 2 um first spacing)
"""

import math
import sys

mode = sys.argv[1] if len(sys.argv) > 1 else "coarse"

Rn = 6.35e-3          # nose radius [m]
delta = math.radians(25.0)   # cone half-angle
Lx = 0.05             # cone streamwise extension [m]
Rout = 3.0*Rn         # outer boundary radius at the nose
slant = math.radians(35.0)   # outer boundary slope over the cone
alpha = math.radians(2.0)    # wedge half-angle

phit = math.pi/2 - delta     # tangency polar angle from stagnation dir

if mode == "coarse":
    nPhi, nCone, nRad = 40, 80, 60
    gradWall = 30.0
else:
    nPhi, nCone, nRad = 200, 400, 200
    gradWall = 136.0

# --- meridian-plane points -------------------------------------------------
def bodyArc(phi):
    return (-Rn*math.cos(phi), Rn*math.sin(phi))

def outerArc(phi):
    return (-Rout*math.cos(phi), Rout*math.sin(phi))

S = bodyArc(0.0)       # stagnation point (on axis)
O = outerArc(0.0)      # outer boundary on axis
Pt = bodyArc(phit)     # body tangency
Qt = outerArc(phit)    # outer tangency

xEnd = Pt[0] + Lx
Eb = (xEnd, Pt[1] + Lx*math.tan(delta))            # cone end (body)
Eo = (xEnd, Qt[1] + (xEnd - Qt[0])*math.tan(slant))  # outer end

# --- wedge vertices ----------------------------------------------------------
# axis points collapse to a single vertex; off-axis points get z = -/+
verts = []
def addAxis(p):
    verts.append((p[0], 0.0, 0.0))
    return len(verts) - 1

def addPair(p):
    y = p[1]*math.cos(alpha)
    z = p[1]*math.sin(alpha)
    verts.append((p[0], y, -z))
    verts.append((p[0], y, z))
    return len(verts) - 2, len(verts) - 1

iS = addAxis(S)
iO = addAxis(O)
iPtm, iPtp = addPair(Pt)
iQtm, iQtp = addPair(Qt)
iEbm, iEbp = addPair(Eb)
iEom, iEop = addPair(Eo)

# --- arc interpolation points ------------------------------------------------
def arcMid(radiusFn, sign):
    p = radiusFn(phit/2)
    y = p[1]*math.cos(alpha)
    z = p[1]*math.sin(alpha)*sign
    return (p[0], y, z)

arcs = [
    ("arc", iS, iPtm, arcMid(bodyArc, -1)),
    ("arc", iS, iPtp, arcMid(bodyArc, +1)),
    ("arc", iO, iQtm, arcMid(outerArc, -1)),
    ("arc", iO, iQtp, arcMid(outerArc, +1)),
]

# --- write dict ---------------------------------------------------------------
def v3(t):
    return f"({t[0]:.8f} {t[1]:.8f} {t[2]:.8f})"

out = []
out.append("""/*--------------------------------*- C++ -*----------------------------------*\\
  =========                 |
  \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\\\    /   O peration     | Website:  https://openfoam.org
    \\\\  /    A nd           | Version:  13
     \\\\/     M anipulation  |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    format      ascii;
    class       dictionary;
    object      blockMeshDict;
}
// Generated by makeBlockMeshDict.py - do not edit by hand
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

convertToMeters 1;

vertices
(""")
for i, t in enumerate(verts):
    out.append(f"    {v3(t)}    // {i}")
out.append(");");

out.append(f"""
blocks
(
    // A: nose region (local x: stagnation->tangency, y: wall->outer)
    hex ({iS} {iPtm} {iQtm} {iO} {iS} {iPtp} {iQtp} {iO})
    ({nPhi} {nRad} 1) simpleGrading (1 {gradWall} 1)

    // B: cone region (local x: tangency->end, y: wall->outer)
    hex ({iPtm} {iEbm} {iEom} {iQtm} {iPtp} {iEbp} {iEop} {iQtp})
    ({nCone} {nRad} 1) simpleGrading (1 {gradWall} 1)
);

edges
(""")
for kind, a, b, m in arcs:
    out.append(f"    {kind} {a} {b} {v3(m)}")
out.append(");");

out.append(f"""
boundary
(
    wall
    {{
        type wall;
        faces
        (
            ({iS} {iS} {iPtp} {iPtm})
            ({iPtm} {iPtp} {iEbp} {iEbm})
        );
    }}

    inlet
    {{
        type patch;
        faces
        (
            ({iO} {iQtm} {iQtp} {iO})
            ({iQtm} {iEom} {iEop} {iQtp})
        );
    }}

    outlet
    {{
        type patch;
        faces
        (
            ({iEbm} {iEbp} {iEop} {iEom})
        );
    }}

    wedge0
    {{
        type wedge;
        faces
        (
            ({iS} {iPtm} {iQtm} {iO})
            ({iPtm} {iEbm} {iEom} {iQtm})
        );
    }}

    wedge1
    {{
        type wedge;
        faces
        (
            ({iS} {iO} {iQtp} {iPtp})
            ({iPtp} {iQtp} {iEop} {iEbp})
        );
    }}
);

// ************************************************************************* //""")

with open("system/blockMeshDict", "w") as f:
    f.write("\n".join(out) + "\n")

h = Rn*2  # radial extent at the nose
r = gradWall**(1.0/(nRad - 1))
d1 = h*(r - 1)/(r**nRad - 1)
print(f"blockMeshDict written ({mode}): {nPhi}+{nCone} x {nRad} cells "
      f"= {(nPhi + nCone)*nRad}, first wall cell ~{d1*1e6:.1f} um at the nose")
