#!/bin/sh
cd ${0%/*} || exit 1
export MPP_DATA_DIRECTORY="$(cd ../nonEqTTv && pwd)/mutation-data-noel"
rm -rf 0
cp -r 0.bak 0
blockMesh > log.blockMesh 2>&1 || { cat log.blockMesh; exit 1; }
foamRun > log.foamRun 2>&1 || { tail -30 log.foamRun; exit 1; }
python3 check-wall.py
