"""Generates system/blockMeshDict for the Mach 20 reacting cylinder
(Casseau et al. Part Two, Sec. 3.2): 2D planar half-domain (symmetry at
y=0) around a circular cylinder of radius R=1 m, streamwise extent
-1.8 m (upstream, Table 2 domain) to +5 m (wake).

Two polar blocks (theta measured from the +x axis, so the upstream
stagnation direction is theta=180 deg):
  A: theta in [0, 90]    (leeward quarter + wake)
  B: theta in [90, 180]  (windward quarter)
The inner edge is the cylinder (true arcs); the outer boundary radius
grows smoothly from 1.8 m upstream to 5 m downstream (spline edges):
  R_out(theta) = 1.8 + (5-1.8)*((1+cos(theta))/2)^2

Radial grading is a single expansion ratio per block, so the first-cell
size scales with the local radial extent: the quoted first-cell size
holds on the windward side (radial extent 0.8 m), which is where the
paper comparison lives; on the wake side it is ~5x larger.

Usage: python3 makeBlockMeshDict.py [coarse|fine]
  coarse: 2 x 45 x 100,  first windward wall cell ~21 um (local checks)
  fine:   2 x 300 x 260, first windward wall cell ~2 um (cluster; paper
          mesh is 155k cells with 2 um first spacing)
"""

import math
import sys

mode = sys.argv[1] if len(sys.argv) > 1 else "coarse"

R = 1.0               # cylinder radius [m]
RoutUp = 1.8          # outer boundary radius upstream (x = -1.8)
RoutDown = 5.0        # outer boundary radius downstream (x = +5)
h = 0.1               # planar thickness [m] (empty front/back)

if mode == "coarse":
    nTheta, nRad = 45, 100
    gradWall = 3000.0
else:
    nTheta, nRad = 300, 260
    gradWall = 15000.0


def Rout(theta):
    return RoutUp + (RoutDown - RoutUp)*((1.0 + math.cos(theta))/2.0)**2


def inner(theta):
    return (R*math.cos(theta), R*math.sin(theta))


def outer(theta):
    r = Rout(theta)
    return (r*math.cos(theta), r*math.sin(theta))


# --- vertices (z = -h/2 and +h/2) -------------------------------------------
verts = []


def addPair(p):
    verts.append((p[0], p[1], -h/2))
    verts.append((p[0], p[1], +h/2))
    return len(verts) - 2, len(verts) - 1


iI0m, iI0p = addPair(inner(0.0))
iI90m, iI90p = addPair(inner(math.pi/2))
iI180m, iI180p = addPair(inner(math.pi))
iO0m, iO0p = addPair(outer(0.0))
iO90m, iO90p = addPair(outer(math.pi/2))
iO180m, iO180p = addPair(outer(math.pi))

# --- edges -------------------------------------------------------------------
def v3(t):
    return f"({t[0]:.8f} {t[1]:.8f} {t[2]:.8f})"


def splinePts(th0, th1, z, n=24):
    pts = []
    for k in range(1, n):
        th = th0 + (th1 - th0)*k/n
        p = outer(th)
        pts.append((p[0], p[1], z))
    return pts


edges = []
# inner cylinder: true arcs through the mid-angle point
for a, b, thm, z in (
    (iI0m, iI90m, math.pi/4, -h/2), (iI0p, iI90p, math.pi/4, +h/2),
    (iI90m, iI180m, 3*math.pi/4, -h/2), (iI90p, iI180p, 3*math.pi/4, +h/2),
):
    p = inner(thm)
    edges.append(f"    arc {a} {b} {v3((p[0], p[1], z))}")
# outer boundary: splines through sampled R_out(theta)
for a, b, th0, th1, z in (
    (iO0m, iO90m, 0.0, math.pi/2, -h/2), (iO0p, iO90p, 0.0, math.pi/2, +h/2),
    (iO90m, iO180m, math.pi/2, math.pi, -h/2),
    (iO90p, iO180p, math.pi/2, math.pi, +h/2),
):
    pts = " ".join(v3(p) for p in splinePts(th0, th1, z))
    edges.append(f"    spline {a} {b} ({pts})")

# --- write dict ---------------------------------------------------------------
out = []
out.append("""/*--------------------------------*- C++ -*----------------------------------*\\
  =========                 |
  \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\\\    /   O peration     | Website:  https://openfoam.org
    \\\\  /    A nd           | Version:  13
     \\\\/     M anipulation  |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    format      ascii;
    class       dictionary;
    object      blockMeshDict;
}
// Generated by makeBlockMeshDict.py - do not edit by hand
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

convertToMeters 1;

vertices
(""")
for i, t in enumerate(verts):
    out.append(f"    {v3(t)}    // {i}")
out.append(");")

out.append(f"""
blocks
(
    // A: leeward quarter (local x: wall->outer with grading, y: theta 0->90)
    hex ({iI0m} {iO0m} {iO90m} {iI90m} {iI0p} {iO0p} {iO90p} {iI90p})
    ({nRad} {nTheta} 1) simpleGrading ({gradWall} 1 1)

    // B: windward quarter (local x: wall->outer, y: theta 90->180)
    hex ({iI90m} {iO90m} {iO180m} {iI180m} {iI90p} {iO90p} {iO180p} {iI180p})
    ({nRad} {nTheta} 1) simpleGrading ({gradWall} 1 1)
);

edges
(""")
out.extend(edges)
out.append(");")

out.append(f"""
boundary
(
    wall
    {{
        type wall;
        faces
        (
            ({iI0m} {iI0p} {iI90p} {iI90m})
            ({iI90m} {iI90p} {iI180p} {iI180m})
        );
    }}

    // windward quarter of the outer boundary: supersonic free stream in
    inlet
    {{
        type patch;
        faces
        (
            ({iO90m} {iO90p} {iO180p} {iO180m})
        );
    }}

    // leeward quarter: everything leaves the domain (U.n > 0 for x > 0)
    outlet
    {{
        type patch;
        faces
        (
            ({iO0m} {iO0p} {iO90p} {iO90m})
        );
    }}

    // the two y=0 segments (upstream of and behind the cylinder)
    symm
    {{
        type symmetryPlane;
        faces
        (
            ({iI0m} {iI0p} {iO0p} {iO0m})
            ({iI180m} {iI180p} {iO180p} {iO180m})
        );
    }}

    frontAndBack
    {{
        type empty;
        faces
        (
            ({iI0m} {iO0m} {iO90m} {iI90m})
            ({iI90m} {iO90m} {iO180m} {iI180m})
            ({iI0p} {iO0p} {iO90p} {iI90p})
            ({iI90p} {iO90p} {iO180p} {iI180p})
        );
    }}
);

// ************************************************************************* //""")

with open("system/blockMeshDict", "w") as f:
    f.write("\n".join(out) + "\n")

L = RoutUp - R  # windward radial extent
r = gradWall**(1.0/(nRad - 1))
d1 = L*(r - 1)/(r**nRad - 1)
print(f"blockMeshDict written ({mode}): 2 x {nTheta} x {nRad} cells "
      f"= {2*nTheta*nRad}, first windward wall cell ~{d1*1e6:.1f} um")
