#!/bin/sh

cd ${0%/*} || exit 1

# toglie solo quello che viene generato (mesh, risultati, log); tiene 0/ e setup
foamListTimes -rm 2>/dev/null
rm -rf constant/polyMesh postProcessing
rm -f log.blockMesh log.foamRun

# "conditions" lo scrive Allrun: lo tiene solo quando e' Allrun a chiamare Allclean
[ "$1" = keepConditions ] || rm -f conditions

#------------------------------------------------------------------------------
